[pytest]
pythonpath = .
addopts = -v -s --html=report.html --self-contained-html

markers =
    ui: Penanda untuk skenario pengujian Web UI (Playwright)
    api: Penanda untuk skenario pengujian Enterprise API (Requests)
    regression: Penanda untuk gerbong Automated Regression Suite

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S